blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/tiny-frontend/api-cloudflare/discussions
    about: Please ask and answer questions here.